Test target support
JamitLabs/Accio pull request #4
Opened 2019-03-27 18:22 UTC by fredpi

Closes #1.

2019-03-27 23:26 UTC, Jeehut requested changes
Looks good overall, just missing the cleanup of frameworks from build phase at the commented place.

2019-03-27 23:26 UTC, Dschee commented on Sources/AccioKit/Services/XcodeProjectIntegrationService.swift
> +            dependenciesGroup.children.removeAll { $0 == groupToRemove }
Here, you should load the franeworksbuildPhase of the target named like the group (if existing) and remove all frameworks within the group from the frameworks build phase.

2019-03-28 16:11 UTC, Jeehut reviewed
Great work overall, please fix the commented lines and after adding the copy frameworks phase in test targets, it should be good to merge! 👍

2019-03-28 16:11 UTC, Jeehut commented on README.md
> +// swift-tools-version:5.0
Could you also add this change to the `Package.swift` file created by the `init` command?

2019-03-28 16:11 UTC, Jeehut commented on Sources/AccioKit/Services/XcodeProjectIntegrationService.swift
> +        // find groups of which the associated target is not be kept
"is not be kept"? Are you missing a "to" there?

2019-03-28 16:11 UTC, Jeehut commented on Sources/AccioKit/Services/XcodeProjectIntegrationService.swift
> +            frameworkBuildPhase?.files.removeAll { file in groupToRemove.children.compactMap { $0.name }.contains { $0 == file.file?.name } }
How is `groupToRemove.children` here not empty after calling `removeAll` right one line before this?

2019-03-28 16:11 UTC, Jeehut commented on Sources/AccioKit/Services/XcodeProjectIntegrationService.swift
> +        let dependenciesPath = "\(workingDirectory)/\(Constants.dependenciesPath)/*"
Why the `/*` suffix? That's not needed afaik when running `rm -rf`.

2019-03-28 16:11 UTC, Jeehut commented on Sources/AccioKit/Services/XcodeProjectIntegrationService.swift
> +        let copiedFrameworkProducts: [FrameworkProduct] = try copy(frameworkProducts: frameworkProducts, of: appTarget, to: dependenciesPlatformPath)
Nice catch there. 👍

2019-03-28 16:20 UTC, fredpi commented on Sources/AccioKit/Services/XcodeProjectIntegrationService.swift
> +            frameworkBuildPhase?.files.removeAll { file in groupToRemove.children.compactMap { $0.name }.contains { $0 == file.file?.name } }
Oh my bad 🤦‍♂️

2019-03-29 10:03 UTC, Jeehut approved these changes

2019-03-29 10:04 UTC, Dschee commented
Thank you for this, looks good, merging.

2019-03-29 10:04 UTC, merged